### ISSUE TITLE
Please make this a website

### ISSUE THREAD

**Issue by codebam** [Nowosad/colorblindcheck#3]

**Comment by Nowosad** [comment]
Hi @codebam -- could you elaborate more on that? What kind of a website you would like to see?

**Comment by codebam** [comment]
I came across your tool while searching to figure out if my color palette for a website was accessible. I can clone the repo and use R, but I think it would be a very useful tool if it was made into an interactive website where you can choose colors.

I realize that may be completely out of scope though, so sorry.

**Comment by Nowosad** [comment]
Hi @codebam -- this is not entirely out of scope (I think). See https://twitter.com/MartijnTennekes/status/1496540597993320455/photo/1 -- there is an interactive package called cols4all that seems to be suiting your needs. Maybe @mtennekes plan to make it a website...

**Comment by mtennekes** [comment]
> Hi @codebam -- this is not entirely out of scope (I think). See https://twitter.com/MartijnTennekes/status/1496540597993320455/photo/1 -- there is an interactive package called cols4all that seems to be suiting your needs. Maybe @mtennekes plan to make it a website...

Yes indeed. We will host the tool soon.
