### ISSUE TITLE
Use bivariate palette for `palette_bivariate_plot()`

### ISSUE THREAD

**Issue by fkohrt** [Nowosad/colorblindcheck#4]
The example code for `palette_bivariate_plot()` uses the palette `rcartocolor::carto_pal(4, "Sunset")`, though that isn't a bivariate palette:

https://github.com/Nowosad/colorblindcheck/blob/7fd8c069698df2dd2cc5f8cb278dc20a7b6113e7/R/palette_plot.R#L69-L83

Wouldn't it be less confusing to use a bivariate palette for this?

```r
colorblindcheck::palette_bivariate_plot(x = pals::brewer.seqseq1())
```

**Comment by Nowosad** [comment]
Hi @fkohrt -- thanks for the suggestion. To explain my decision to use rcartocolor in that example -- I just did not want to add another (soft) dependency to this package. 

What do you think about adding your example as a comment in the examples section?

**Comment by fkohrt** [comment]
I see, makes sense.

That is a great suggestion!
